version: "3.9"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "11.1.1.100/24"

services:
  diploma:
    networks:
      network:
        ipv4_address: 11.1.1.11
    image: gmonitor/diploma:master
    env_file:
      - .env
    ports:
      - "8000:8000"
    container_name: diploma
    depends_on:
      - postgres


  admin:
    networks:
      network:
        ipv4_address: 11.1.1.13
    image: gmonitor/diploma:master
    env_file:
      - .env
    ports:
      - "7000:7000"
    container_name: admin
    entrypoint: [ "gunicorn", "--workers", "4", "--bind", "0.0.0.0:7000", "-m", "007", "admin.wsgi:app" ]
    depends_on:
      - diploma


  postgres:
    networks:
      network:
        ipv4_address: 11.1.1.100
    image: postgres:13.3
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
#    volumes:
#      - /data/postgresql/bot:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U diploma -d diploma_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
